augment_epoch: 10
backbone: RN50
dataset: image
init_alpha: 3
init_beta: 1
load_cache: false
load_pre_feat: false
lr: 0.001
root_path: ./data/
search_hp: true
search_scale:
- 12
- 5
search_step:
- 200
- 20
shots: 16
train_epoch: 20
